export const Foods = [
  {
    id: 1,
    img: "/soup1.png",
    title: "Spicy seasoned seafood noodles",
    price: 2.29,
    available: 20,
    category: "hot-dishes",
  },
  {
    id: 2,
    img: "/soup2.png",
    title: "Salted Pasta with mushroom sauce",
    price: 2.69,
    available: 11,
    category: "hot-dishes",
  },
  {
    id: 3,
    img: "/soup3.png",
    title: "Beef dumpling in hot and sour soup",
    price: 2.99,
    available: 16,
    category: "soup",
  },
  {
    id: 4,
    img: "/soup4.png",
    title: "Healthy noodle with spinach leaf",
    price: 3.29,
    available: 22,
    category: "cold-dishes",
  },

  {
    id: 5,
    img: "/soup1.png",
    title: "Grilled chicken with herbs",
    price: 4.99,
    available: 18,
    category: "grill",
  },
  {
    id: 6,
    img: "/soup2.png",
    title: "Crispy spring rolls",
    price: 1.99,
    available: 30,
    category: "appetizer",
  },
  {
    id: 7,
    img: "/soup3.png",
    title: "Chocolate lava cake",
    price: 3.49,
    available: 12,
    category: "dissert",
  },
  {
    id: 8,
    img: "/soup4.png",
    title: "Seafood tom yum soup",
    price: 3.79,
    available: 14,
    category: "soup",
  },

  {
    id: 9,
    img: "/soup1.png",
    title: "Grilled beef steak",
    price: 6.99,
    available: 9,
    category: "grill",
  },
  {
    id: 10,
    img: "/soup2.png",
    title: "Avocado salad with lemon",
    price: 2.59,
    available: 25,
    category: "cold-dishes",
  },
  {
    id: 11,
    img: "/soup3.png",
    title: "Spicy fried rice",
    price: 2.89,
    available: 19,
    category: "hot-dishes",
  },
  {
    id: 12,
    img: "/soup4.png",
    title: "Chicken corn soup",
    price: 2.49,
    available: 17,
    category: "soup",
  },

  {
    id: 13,
    img: "/soup1.png",
    title: "Garlic grilled shrimp",
    price: 5.49,
    available: 13,
    category: "grill",
  },
  {
    id: 14,
    img: "/soup2.png",
    title: "Cheese sticks",
    price: 2.19,
    available: 28,
    category: "appetizer",
  },
  {
    id: 15,
    img: "/soup3.png",
    title: "Vanilla ice cream",
    price: 1.99,
    available: 40,
    category: "dissert",
  },
  {
    id: 16,
    img: "/soup4.png",
    title: "Cold sesame noodles",
    price: 2.79,
    available: 21,
    category: "cold-dishes",
  },

  {
    id: 17,
    img: "/soup1.png",
    title: "Hot chili chicken",
    price: 3.99,
    available: 15,
    category: "hot-dishes",
  },
  {
    id: 18,
    img: "/soup2.png",
    title: "Miso soup",
    price: 1.89,
    available: 26,
    category: "soup",
  },
  {
    id: 19,
    img: "/soup3.png",
    title: "Fruit platter",
    price: 2.29,
    available: 34,
    category: "dissert",
  },
  {
    id: 20,
    img: "/soup4.png",
    title: "Mini chicken sandwiches",
    price: 2.99,
    available: 20,
    category: "appetizer",
  },
];
